global:
  message-format: '[{channelno}{channel}] [{prefix}{player}{suffix}&f] {message}'
  join-format: '[{channelno}{channel}] {player} joined channel.'
  quit-format: '[{channelno}{channel}] {player} left channel.'
irc:
  networks:

