global:
  message-format: '[{channelno}{channel}] [{prefix}{player}{suffix}&f] {message}'
  channel-format: '[{channelno}{channel}] {message}'
  roma-to-hira-format: '{message} &f({converted})'
irc:
  default-say: false
  networks:
    freenode:
      enabled: false
      host: irc.freenode.net
      port: 6667
      nick: ElChat
      charset: UTF-8
      channels:
        '#YourChannel':
          title: IRC
          forwards: [ global, dynmap ]

